#!/usr/bin/env bash
set -euo pipefail
WF="$(cd "$(dirname "$0")/.." && pwd)/.github/workflows/pre-ci-review-evidence.yml"
test -s "$WF"
grep -q 'environment: read-business' "$WF"
grep -q 'environment: review' "$WF"
grep -q 'candidate_sha' "$WF"
grep -q 'expected_current_sha' "$WF"
grep -q 'service:' "$WF"
grep -q 'forward-only' "$WF"
grep -q 'ICOM_DEPLOY_REVIEWER_SIGNING_KEY' "$WF"
grep -q 'creator_discovery_phase1_api_scope' "$WF"
grep -q 'creator_intelligence_phase2_api_scope' "$WF"
grep -q 'migration_41_scope' "$WF"
grep -q 'migration_42_scope' "$WF"
grep -q 'auto_invite_send_unchanged' "$WF"
grep -q 'auto_invite_configuration_unchanged' "$WF"
grep -q 'backorder_classification_unchanged' "$WF"
grep -q 'unrelated_api_paths_rejected' "$WF"
grep -q 'candidate_tree_sha' "$WF"
grep -q 'source_repository' "$WF"
grep -q 'apps/api/app/cron/affiliate-creator-discovery/route.ts' "$WF"
grep -q 'apps/api/app/cron/affiliate-creator-metric-refresh/route.ts' "$WF"
grep -q 'apps/api/lib/affiliate-creator-metric-refresh.ts' "$WF"
grep -q 'apps/api/lib/__tests__/affiliate-creator-metric-refresh.test.ts' "$WF"
grep -q 'scripts/icom-affiliate-creator-sync.sh' "$WF"
grep -q 'scripts/cron.d/icom-affiliate-creator-sync' "$WF"
grep -q 'scripts/patch-cron-allowlist-affiliate-creator-sync.sh' "$WF"
grep -q 'scripts/__tests__/icom-affiliate-creator-sync.test.sh' "$WF"
grep -q '20260916_41_affiliate_creator_discovery_metadata.sql' "$WF"
grep -q '20260916_42_affiliate_creator_sync_runs.sql' "$WF"
grep -q '20260916_42_affiliate_creator_sync_runs_ROLLBACK.sql' "$WF"
grep -q '20260916_42_affiliate_creator_sync_runs_VERIFY.sql' "$WF"
! grep -Eq 'apps/api/(app|lib)/\*' "$WF"
! grep -Eq 'contents: write|packages: write|deploy-approved|owner-deploy|docker (run|stop|rm)' "$WF"
echo 'PASS: pre-CI reviewer producer preserves read/sign separation and has no deploy authority.'
